language: node_js
node_js:
  - "8"
  
git:
  submodules: false

before_install:
  - npm install -g grunt-cli
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - NPM_CONFIG_PROGRESS="false"

matrix:
  fast_finish: true

script:
  - grunt dist --verbose
  - grunt jshint --verbose
  - grunt test --verbose
