language: node_js
node_js:
  - "14"

cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - NPM_CONFIG_PROGRESS="false"

matrix:
  fast_finish: true

script:
  - yarn run eslint js/
  - grunt jshint --verbose
  - grunt test --verbose
