language: node_js
node_js:
  - "6"
before_install:
  - npm install -g grunt-cli
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
matrix:
  fast_finish: true
script:
  - grunt dist --verbose
  - grunt jshint --verbose
  - grunt test --verbose
