name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn prettier --check
      - run: yarn lint
      - run: yarn test
      - run: yarn test-module

  publish-npm:
    needs: test
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
